version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3000"
    networks:
      - my-network
    environment:
      - NODE_ENV=development
    volumes:
      - "./product-service:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      - mongodb

  inventory-service:
    build: ./inventory-service
    ports:
      - "3002:3000"
    networks:
      - my-network
    environment:
      - NODE_ENV=development
    volumes:
      - "./inventory-service:/usr/src/app"
      - "/usr/src/app/node_modules"

  order-service:
    build: ./order-service
    ports:
      - "3003:3000"
    networks:
      - my-network
    environment:
      - NODE_ENV=development
    volumes:
      - "./order-service:/usr/src/app"
      - "/usr/src/app/node_modules"

  payment-service:
    build: ./payment-service
    ports:
      - "3004:3000"
    networks:
      - my-network
    environment:
      - NODE_ENV=development
    volumes:
      - "./payment-service:/usr/src/app"
      - "/usr/src/app/node_modules"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  mongodb:
    image: "mongo:latest"
    ports:
      - "27018:27017"
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
